name: melkalk
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 13.0.0+13

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  yandex_mobileads: ^7.7.0
#  google_mobile_ads: ^0.13.6
#  flutter_yandex_mobile_ads: ^0.0.9
  shared_preferences: ^2.3.3
  intl: ^0.20.2
  go_router: ^14.6.2
  get_it: ^8.0.3
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    # Add assets from the images directory to the application.
    - assets/images/
# run: flutter clean && flutter pub get && flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#0277bd"
  image: assets/splashnew.png
  android: true
  ios: true



  # color: "#ffffff"
  # image: assets/splash_full.png
  # color_dark: "#1a1a1a"
  # image_dark: assets/splash_full.png
  # android: true
  # ios: true
  # android_gravity: fill
  # ios_content_mode: scaleAspectFill